// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Db;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(DMADbContext))]
    [Migration("20240620204307_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Models.Adc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Adces");
                });

            modelBuilder.Entity("Web.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<int?>("ReissueId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GenreId");

                    b.HasIndex("LabelId");

                    b.HasIndex("ReissueId");

                    b.HasIndex("YearId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Web.Models.Amplifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Amplifiers");
                });

            modelBuilder.Entity("Web.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Web.Models.Bitness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Data")
                        .HasColumnType("int");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bitnesses");
                });

            modelBuilder.Entity("Web.Models.Cartrige", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cartriges");
                });

            modelBuilder.Entity("Web.Models.Codec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Codecs");
                });

            modelBuilder.Entity("Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Web.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Web.Models.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("Web.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Web.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Web.Models.Processing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Processings");
                });

            modelBuilder.Entity("Web.Models.Reissue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Data")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reissues");
                });

            modelBuilder.Entity("Web.Models.Sampling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Data")
                        .HasColumnType("int");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Samplings");
                });

            modelBuilder.Entity("Web.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechicalInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Web.Models.TechnicalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdcId")
                        .HasColumnType("int");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int?>("AmplifierId")
                        .HasColumnType("int");

                    b.Property<int?>("BitnessId")
                        .HasColumnType("int");

                    b.Property<int?>("CartrigeId")
                        .HasColumnType("int");

                    b.Property<int?>("CodecId")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("FormatId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessingId")
                        .HasColumnType("int");

                    b.Property<int?>("SamplingId")
                        .HasColumnType("int");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdcId");

                    b.HasIndex("AlbumId")
                        .IsUnique()
                        .HasFilter("[AlbumId] IS NOT NULL");

                    b.HasIndex("AmplifierId");

                    b.HasIndex("BitnessId");

                    b.HasIndex("CartrigeId");

                    b.HasIndex("CodecId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("FormatId");

                    b.HasIndex("ProcessingId");

                    b.HasIndex("SamplingId");

                    b.HasIndex("StateId");

                    b.ToTable("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Data")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("Web.Models.Album", b =>
                {
                    b.HasOne("Web.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Models.Country", "Country")
                        .WithMany("Albums")
                        .HasForeignKey("CountryId");

                    b.HasOne("Web.Models.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Models.Label", "Label")
                        .WithMany("Albums")
                        .HasForeignKey("LabelId");

                    b.HasOne("Web.Models.Reissue", "Reissue")
                        .WithMany("Albums")
                        .HasForeignKey("ReissueId");

                    b.HasOne("Web.Models.Year", "Year")
                        .WithMany("Albums")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Country");

                    b.Navigation("Genre");

                    b.Navigation("Label");

                    b.Navigation("Reissue");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("Web.Models.TechnicalInfo", b =>
                {
                    b.HasOne("Web.Models.Adc", "Adc")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("AdcId");

                    b.HasOne("Web.Models.Album", "Album")
                        .WithOne("TechnicalInfo")
                        .HasForeignKey("Web.Models.TechnicalInfo", "AlbumId");

                    b.HasOne("Web.Models.Amplifier", "Amplifier")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("AmplifierId");

                    b.HasOne("Web.Models.Bitness", "Bitness")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("BitnessId");

                    b.HasOne("Web.Models.Cartrige", "Cartrige")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("CartrigeId");

                    b.HasOne("Web.Models.Codec", "Codec")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("CodecId");

                    b.HasOne("Web.Models.Device", "Device")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("DeviceId");

                    b.HasOne("Web.Models.Format", "Format")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("FormatId");

                    b.HasOne("Web.Models.Processing", "Processing")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("ProcessingId");

                    b.HasOne("Web.Models.Sampling", "Sampling")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("SamplingId");

                    b.HasOne("Web.Models.State", "State")
                        .WithMany("TechnicalInfos")
                        .HasForeignKey("StateId");

                    b.Navigation("Adc");

                    b.Navigation("Album");

                    b.Navigation("Amplifier");

                    b.Navigation("Bitness");

                    b.Navigation("Cartrige");

                    b.Navigation("Codec");

                    b.Navigation("Device");

                    b.Navigation("Format");

                    b.Navigation("Processing");

                    b.Navigation("Sampling");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Web.Models.Adc", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Album", b =>
                {
                    b.Navigation("TechnicalInfo");
                });

            modelBuilder.Entity("Web.Models.Amplifier", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Web.Models.Bitness", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Cartrige", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Codec", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Country", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Web.Models.Device", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Format", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Genre", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Web.Models.Label", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Web.Models.Processing", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Reissue", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Web.Models.Sampling", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.State", b =>
                {
                    b.Navigation("TechnicalInfos");
                });

            modelBuilder.Entity("Web.Models.Year", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
