// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Db;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Adc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Adces");
                });

            modelBuilder.Entity("DMA.Domain.Albums.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.HasIndex("Title");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Amplifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Amplifiers");
                });

            modelBuilder.Entity("DMA.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Bitness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Bitnesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Value = 24
                        },
                        new
                        {
                            Id = 3,
                            Value = 32
                        },
                        new
                        {
                            Id = 4,
                            Value = 64
                        });
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Cartridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cartridges");
                });

            modelBuilder.Entity("DMA.Domain.Posts.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.DigitalFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DigitalFormats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FLAC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DSD64"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DSD128"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DSD256"
                        },
                        new
                        {
                            Id = 5,
                            Name = "DSD512"
                        },
                        new
                        {
                            Id = 6,
                            Name = "WV"
                        });
                });

            modelBuilder.Entity("DMA.Domain.Albums.EquipmentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdcId")
                        .HasColumnType("int");

                    b.Property<int?>("AmplifierId")
                        .HasColumnType("int");

                    b.Property<int?>("CartridgeId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("WireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdcId");

                    b.HasIndex("AmplifierId");

                    b.HasIndex("CartridgeId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WireId");

                    b.ToTable("EquipmentInfos");
                });

            modelBuilder.Entity("DMA.Domain.Albums.FormatInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BitnessId")
                        .HasColumnType("int");

                    b.Property<int?>("DigitalFormatId")
                        .HasColumnType("int");

                    b.Property<int?>("SamplingId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceFormatId")
                        .HasColumnType("int");

                    b.Property<int?>("VinylStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BitnessId");

                    b.HasIndex("DigitalFormatId");

                    b.HasIndex("SamplingId");

                    b.HasIndex("SourceFormatId");

                    b.HasIndex("VinylStateId");

                    b.ToTable("FormatInfos");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DMA.Domain.Posts.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDraft");

                    b.HasIndex("Title");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("DMA.Domain.Posts.PostCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PostId");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Reissue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Reissues");
                });

            modelBuilder.Entity("DMA.Domain.Albums.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Discogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipmentInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("FormatInfoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFirstPress")
                        .HasColumnType("bit");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<int?>("ReissueId")
                        .HasColumnType("int");

                    b.Property<double?>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StorageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CountryId");

                    b.HasIndex("EquipmentInfoId");

                    b.HasIndex("FormatInfoId");

                    b.HasIndex("LabelId");

                    b.HasIndex("ReissueId");

                    b.HasIndex("StorageId");

                    b.HasIndex("YearId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Sampling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Samplings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = 96.0
                        },
                        new
                        {
                            Id = 2,
                            Value = 192.0
                        },
                        new
                        {
                            Id = 3,
                            Value = 384.0
                        },
                        new
                        {
                            Id = 4,
                            Value = 2.7999999999999998
                        },
                        new
                        {
                            Id = 5,
                            Value = 5.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Value = 11.199999999999999
                        },
                        new
                        {
                            Id = 7,
                            Value = 22.5
                        });
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.SourceFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourceFormats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LP 12'' 33RPM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EP 10'' 45RPM"
                        },
                        new
                        {
                            Id = 3,
                            Name = "EP 12'' 45RPM"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SINGLE 7'' 45RPM"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SINGLE 12'' 45RPM"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SHELLAC 10'' 78RPM"
                        });
                });

            modelBuilder.Entity("DMA.Domain.Statistics.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.VinylState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VinylStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mint"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Near Mint"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Very Good+"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Very Good"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Good"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Wire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wires");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Years");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DMA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DMA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DMA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Adc", b =>
                {
                    b.HasOne("DMA.Domain.Equipment.Manufacturer", "Manufacturer")
                        .WithMany("Adcs")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DMA.Domain.Albums.Album", b =>
                {
                    b.HasOne("DMA.Domain.ReferenceData.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMA.Domain.ReferenceData.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Amplifier", b =>
                {
                    b.HasOne("DMA.Domain.Equipment.Manufacturer", "Manufacturer")
                        .WithMany("Amplifiers")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Cartridge", b =>
                {
                    b.HasOne("DMA.Domain.Equipment.Manufacturer", "Manufacturer")
                        .WithMany("Cartridges")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DMA.Domain.Albums.EquipmentInfo", b =>
                {
                    b.HasOne("DMA.Domain.Equipment.Adc", "Adc")
                        .WithMany()
                        .HasForeignKey("AdcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.Equipment.Amplifier", "Amplifier")
                        .WithMany()
                        .HasForeignKey("AmplifierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.Equipment.Cartridge", "Cartridge")
                        .WithMany()
                        .HasForeignKey("CartridgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.Equipment.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.Equipment.Wire", "Wire")
                        .WithMany()
                        .HasForeignKey("WireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Adc");

                    b.Navigation("Amplifier");

                    b.Navigation("Cartridge");

                    b.Navigation("Player");

                    b.Navigation("Wire");
                });

            modelBuilder.Entity("DMA.Domain.Albums.FormatInfo", b =>
                {
                    b.HasOne("DMA.Domain.ReferenceData.Bitness", "Bitness")
                        .WithMany()
                        .HasForeignKey("BitnessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.ReferenceData.DigitalFormat", "DigitalFormat")
                        .WithMany()
                        .HasForeignKey("DigitalFormatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.ReferenceData.Sampling", "Sampling")
                        .WithMany()
                        .HasForeignKey("SamplingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.ReferenceData.SourceFormat", "SourceFormat")
                        .WithMany()
                        .HasForeignKey("SourceFormatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.ReferenceData.VinylState", "VinylState")
                        .WithMany()
                        .HasForeignKey("VinylStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bitness");

                    b.Navigation("DigitalFormat");

                    b.Navigation("Sampling");

                    b.Navigation("SourceFormat");

                    b.Navigation("VinylState");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Player", b =>
                {
                    b.HasOne("DMA.Domain.Equipment.Manufacturer", "Manufacturer")
                        .WithMany("Players")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DMA.Domain.Posts.PostCategory", b =>
                {
                    b.HasOne("DMA.Domain.Posts.Category", "Category")
                        .WithMany("PostCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMA.Domain.Posts.Post", "Post")
                        .WithMany("PostCategories")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DMA.Domain.Albums.Release", b =>
                {
                    b.HasOne("DMA.Domain.Albums.Album", "Album")
                        .WithMany("Releases")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMA.Domain.ReferenceData.Country", "Country")
                        .WithMany("Releases")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.Albums.EquipmentInfo", "EquipmentInfo")
                        .WithMany()
                        .HasForeignKey("EquipmentInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMA.Domain.Albums.FormatInfo", "FormatInfo")
                        .WithMany()
                        .HasForeignKey("FormatInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMA.Domain.ReferenceData.Label", "Label")
                        .WithMany("Releases")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.ReferenceData.Reissue", "Reissue")
                        .WithMany("Releases")
                        .HasForeignKey("ReissueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.ReferenceData.Storage", "Storage")
                        .WithMany("Releases")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMA.Domain.ReferenceData.Year", "Year")
                        .WithMany("Releases")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");

                    b.Navigation("Country");

                    b.Navigation("EquipmentInfo");

                    b.Navigation("FormatInfo");

                    b.Navigation("Label");

                    b.Navigation("Reissue");

                    b.Navigation("Storage");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Wire", b =>
                {
                    b.HasOne("DMA.Domain.Equipment.Manufacturer", "Manufacturer")
                        .WithMany("Wires")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DMA.Domain.Albums.Album", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("DMA.Domain.Posts.Category", b =>
                {
                    b.Navigation("PostCategories");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Country", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Genre", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Label", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("DMA.Domain.Equipment.Manufacturer", b =>
                {
                    b.Navigation("Adcs");

                    b.Navigation("Amplifiers");

                    b.Navigation("Cartridges");

                    b.Navigation("Players");

                    b.Navigation("Wires");
                });

            modelBuilder.Entity("DMA.Domain.Posts.Post", b =>
                {
                    b.Navigation("PostCategories");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Reissue", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Storage", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("DMA.Domain.ReferenceData.Year", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
